# Generated by Django 2.2.1 on 2019-06-07 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_number', models.CharField(max_length=255)),
                ('recipient_address', models.CharField(max_length=255)),
                ('zone', models.CharField(choices=[('AJAH', 'Ajah'), ('LEKKI', 'Lekki'), ('IKATE', 'Ikate'), ('IKOYI', 'Ikoyi')], max_length=8)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.IntegerField(default=220)),
                ('amount', models.IntegerField()),
                ('method', models.CharField(choices=[('TRANSFER', 'Wire Transfer'), ('CARD', 'Debit Card')], max_length=8)),
                ('confirmed', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diesel.Order')),
            ],
        ),
    ]
